version: '3'
services:
  #Authentication Service
  authentication-service:
    build: ./authentication-service/AuthenticationService
    container_name: authentication-service
    ports:
      - 6060:80
    networks:
      - network-name

  #Kwetter Frontend
  kwetter-frontend:
    build: ./kwetter-frontend
    container_name: kwetter-frontend
    # env_file: .kf.env
    ports:
      - 3000:80
    networks:
      - network-name

  #Profile Service
  profile-service:
    build: ./profile-service/ProfileService
    container_name: profile-service
    ports:
      - 53231:80
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
