version: '3'
services:
  #Authentication Service
  authentication-service:
    build: ./authentication-service/AuthenticationService
    container_name: authentication-service
    restart: always
    ports:
      - 6060:80
    networks:
      - network-name

  #SQL Express Authentication
  sql-express-authentication:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 1Secure*Password1
    container_name: sql-express-authentication
    ports:
      - 1401:1433
    networks:
      - network-name

  #Kwetter Frontend
  kwetter-frontend:
    build: ./kwetter-frontend
    container_name: kwetter-frontend
    # env_file: .kf.env
    ports:
      - 3000:80
    networks:
      - network-name

  #Profile Service
  profile-service:
    build: ./profile-service/ProfileService
    container_name: profile-service
    restart: always
    ports:
      - 53231:80
    networks:
      - network-name
  
  #SQL Express Profile
  sql-express-profile:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 1Secure*Password1
    container_name: sql-express-profile
    ports:
      - 1402:1433
    networks:
      - network-name
  
  #RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
