version: '3'
services:
  #Authentication Service
  as:
    image: dennycox/authentication-service
    container_name: authentication-service
    env_file: .kf.env
    ports:
      - ${AS_PORT}:80
    networks:
      - network-name

  #Kwetter Frontend
  kf:
    image: dennycox/kwetter-frontend
    container_name: kwetter-frontend
    ports:
      - ${KF_PORT}:80
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
