apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: dennycox/profile-service:latest
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ConnectionStrings:DefaultConnection
            value: Server=sql-express-profile,1433;Database=TransferData;User ID=SA;Password=1Secure*Password1;
          - name: ASPNETCORE_ConnectionStrings:RabbitMqConnectionString
            value: amqp://guest:guest@rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
