apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      restartPolicy: Always
      containers:
      - name: authentication
        image: dennycox/authentication-service:latest
        resources: {}
        ports:
          - containerPort: 80
        env:
        - name: 'ASPNETCORE_ConnectionStrings__DefaultConnection'
          value: 'Server=tcp:kwetter-i4034511.database.windows.net,1433;Initial Catalog=authentication-service-db-test;Persist Security Info=False;User ID=admin-denny;Password=Password-1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        - name: 'ASPNETCORE_ConnectionStrings__RabbitMqConnectionString'
          value: 'amqp://guest:guest@rabbitmq:5672'
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
