apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kwetter-frontend-deployment
spec:
  selector:
    matchLabels:
    app: kwetter-frontend
  replicas: 1
  template:
    metadata:
    labels:
      app: kwetter-frontend
    spec:
    containers:
      - name: kwetter-frontend
        image: dennycox/kwetter-frontend:latest
        ports:
        - containerPort: 80