apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      restartPolicy: Always
      containers:
      - name: profile
        image: dennycox/profile-service:latest
        env:
        - name: 'ASPNETCORE_ConnectionStrings__DefaultConnection'
          value: 'Server=tcp:kwetter-i4034511.database.windows.net,1433;Initial Catalog=profile-service-db-test;Persist Security Info=False;User ID=admin-denny;Password=Password-1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        - name: 'ASPNETCORE_ConnectionStrings__RabbitMqConnectionString'
          value: 'amqp://guest:guest@rabbitmq:5672'
        resources: {}
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
