apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      restartPolicy: Always
      containers:
      - name: profile
        image: dennycox/profile-service:latest
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ConnectionStrings:DefaultConnection
            value: Server=v4jdd6eb2or2.eu-central-2.psdb.cloud;Database=kwetter-db;user=xid7b94iap6y;password=pscale_pw_rnSKcIO3BRd5w_NsHPuEyzQ2TipXlCjbWKDo7Jfq4hQ;SslMode=VerifyFull;
          - name: ASPNETCORE_ConnectionStrings:RabbitMqConnectionString
            value: amqp://guest:guest@rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
