apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      restartPolicy: Always
      containers:
      - name: profile
        image: dennycox/profile-service:latest
        env:
        - name: 'ASPNETCORE_ConnectionStrings__DefaultConnection'
          value: 'Server=v4jdd6eb2or2.eu-central-2.psdb.cloud;Database=kwetter-db;user=23s7jh5cbg4m;password=pscale_pw_QUr79DimJH30dWzZhtiT0ncjBfXUu7wxpPQ3OlrotXY;SslMode=VerifyFull;'
        - name: 'ASPNETCORE_ConnectionStrings__RabbitMqConnectionString'
          value: 'amqp://guest:guest@rabbitmq:5672'
        resources: {}
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
